source "https://rubygems.org"

gem "rails"
gem "rouge"
gem "kramdown"
gem "therubyracer"
gem "jekyll-press"
gem "jekyll-sitemap"
gem "jekyll-less"
gem "jekyll-redirect-from"
gem "jekyll-last-modified-at"
